language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
cache: cargo
before_script:
    - which rustfmt || cargo install rustfmt
script:
    - rustfmt src/* && git diff --quiet
    - ./test.sh
