language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
cache:
    - cargo: true
    - apt: true
before_script:
    - apt install libdbus-1-dev
    - which rustfmt || cargo install rustfmt
script:
    - rustfmt src/* && git diff --quiet
    - ./test.sh
